### ISSUE TITLE
Failed to write to 'state.settings'. File or folder 'state.settings' does not exist.

### ISSUE THREAD

**Issue by kalzi** [c9/core#431]
Installed C9 via C9 Installer into a docker ubuntu phusion/baseimage container ie..
```
git clone git://github.com/c9/core.git c9sdk
cd c9sdk
scripts/install-sdk.sh
```
Node version 5.x 
Receiving following banner error on load and its persistent at every action from any browser (Chrome | Opera | Firefox)

`Failed to write to 'state.settings'. File or folder 'state.settings' does not exist.`

Created `state.settings` file with `touch ~/.c9/state.settings` yet it still complaining.  

Any suggestions? Not sure how to get the trace info, have enabled `--debug` switch to `server.js` , yet i do not see any difference.

**Comment by nightwing** [comment]
What command did you use for running the server, state.settings should be saved in your workspace folder not in ~/.c9.
Are you able to save other files from cloud9>

**Comment by kalzi** [comment]
@nightwing Thanks for your direction, my issue is fixed by taking ownership of `/workspace`

**Comment by darkcyber** [comment]
hi @kalzi @nightwing  I experiencing this one, could you please tell me more? I have already put state.settings in my workspace folder and .c9 folder and make it world writable and readable. but I'm still facing that error on top of cloud9 interface.

Could you suggest me something? Thanks
